name: ROS 2 Builder

on:
  pull_request:
    branches: [ main  ]
  push:
    branches: [ main ]

 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          #- jazzy
          - kilted
        include:
          # Jazzy Ubuntu 24.04 (Noble)
          #- ros_distribution: jazzy
          #  docker_image: osrf/ros:jazzy-desktop
          #  use_ros2_testing: false
          # Kilted Ubuntu 24.04 (Noble)
          - ros_distribution: kilted
            docker_image: osrf/ros:kilted-desktop
            use_ros2_testing: false

    container:
      image: ${{ matrix.docker_image }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - run: |
          echo "Workspace check 1: $GITHUB_WORKSPACE"
          find "$GITHUB_WORKSPACE" -maxdepth 4 -type d

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@0.7.19
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
          use-ros2-testing: ${{ matrix.use_ros2_testing }}

      - run: |
          echo "Workspace check 2: $GITHUB_WORKSPACE"
          find "$GITHUB_WORKSPACE" -maxdepth 4 -type d
          echo " "
          ls "$GITHUB_WORKSPACE"

      - name: Build and Test
        uses: ros-tooling/action-ros-ci@0.4.5
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
          package-name: bno08x_hardware_interface
          vcs-repo-file-url: "file:${{ github.workspace }}/bno08x_sh2_dependency.repos"
          colcon-defaults: ""
          # no mixin "coverage-gcc" until there are more tests

      - run: |
          echo "Workspace check 3: $GITHUB_WORKSPACE"
          find "$GITHUB_WORKSPACE" -maxdepth 4 -type d
